name: pico_notes
description: A media-centric note taking app.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  drift: ^2.11.0
  path_provider: ^2.0.14
  supabase_flutter: ^1.10.0
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0

  # Authentication
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^5.0.0
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # Utils
  uuid: ^4.0.0
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
