name: pico_notes
description: A media-centric note taking app.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  drift: ^2.11.0
  path_provider: ^2.0.14
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1

  # Authentication
  google_sign_in: ^6.1.0
  sign_in_with_apple: ^7.0.1
  flutter_secure_storage: ^9.0.0
  crypto: ^3.0.3

  # Utils
  uuid: ^4.0.0
  intl: ^0.20.2
  flutter_quill: ^11.4.2
  supabase_flutter: ^2.9.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - media/
    - assets/icons/
    - assets/darkmodecollection/svg/
    - assets/lightmodecollection/svg/
