name: pico_notes
description: A media-centric note taking app.
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sf_symbols: ^0.2.0
  flutter_riverpod: ^2.4.0
  drift: ^2.11.0
  path_provider: ^2.0.14
  supabase_flutter: ^1.10.0
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
